# Generated by Django 4.0.3 on 2022-04-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIpredictionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasting',
            name='forecasting_len',
            field=models.PositiveSmallIntegerField(choices=[('1일', '1일'), ('2일', '2일'), ('3일', '3일'), ('4일', '4일'), ('5일', '5일'), ('6일', '6일'), ('7일', '7일')]),
        ),
    ]
