# Generated by Django 4.0.3 on 2022-04-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIpredictionapp', '0003_alter_forecasting_forecasting_len'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecasting',
            old_name='forecasting_len',
            new_name='forecastinglen',
        ),
    ]
