# Generated by Django 4.0.3 on 2022-05-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
