# Generated by Django 4.0.3 on 2022-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.IntegerField(verbose_name='헨드폰 번호'),
        ),
    ]
